name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build and release phar
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Create target phar name
        id: target
        run: |
          echo "::set-output name=value::server-${{ matrix.php }}.phar"

      - name: Build
        env:
          TARGET: ${{ steps.target.outputs.value }}
        run: |
          composer phar-build
          cp build/server.phar "$TARGET"

      - name: Add to latest release
        if: ${{ github.event_name == 'release' }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.target.outputs.value }}
          tags: true
          update_latest_release: true
          draft: false
