name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build and release phar
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.4']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Create target phar name
        id: target-phar
        run: echo "phar_name=server-${{ matrix.php }}.phar" >> "$GITHUB_ENV"

      - name: Create target composer.lock name
        id: target-composer-lock
        run: echo "lock_name=composer-${{ matrix.php }}.lock" >> "$GITHUB_ENV"

      - name: Create build-specific composer.lock
        env:
          TARGET: ${{ env.lock_name }}
        run: |
          rm -Rf composer.lock
          composer update
          cp composer.lock "$TARGET"
          rm -Rf vendor

      - name: Build
        env:
          TARGET: ${{ env.phar_name }}
        run: |    
          composer phar-build
          cp build/server.phar "$TARGET"

      - name: Add phar, composer.lock to latest release
        if: ${{ github.event_name == 'release' }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ env.phar_name }};${{ env.lock_name }}"
          tags: true
          update_latest_release: true
          draft: false
