name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and release phar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Build
        run: |
          composer phar-build
          cp build/server.phar server.phar

      - name: Add to latest release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "server.phar"
          tags: true
          update_latest_release: true
          draft: false
