name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: PHPUnit unit tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcntl

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-req=ext-pcntl

      - name: Run PHPUnit unit tests
        run: composer test

  phar:
    name: Phar tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcntl

      - name: Build and test
        run: |
          rm -Rf composer.lock
          composer update          
          composer phar-build
          composer server-test-prepare
          ./server.phar &
          composer server-test
